use powerdns;
insert into domains (name,type) values ('rpz.example.net','NATIVE');
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'rpz.example.net', 'SOA', 'LOCALHOST named-mgr.example.net 1 3600 900 2592000 7200', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'rpz.example.net', 'NS', 'LOCALHOST', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'nxdomain.example.com.rpz.example.net', 'CNAME', '.', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'nodata.example.com.rpz.example.net', 'CNAME', '*', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'bad.example.com.rpz.example.net', 'A', '10.0.0.1', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'bad.example.com.rpz.example.net', 'AAAA', '2001:db8::1', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'*.azone.example.com.rpz.example.net', 'CNAME', 'garden.example.net', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'ok.azone.example.com.rpz.example.net', 'CNAME', 'rpz-passthru', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'bzone.example.com.rpz.example.net', 'CNAME', '*.garden.example.net', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'*.bzone.example.com.rpz.example.net', 'CNAME', '*.garden.example.net', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'24.0.2.0.192.rpz-ip.rpz.example.net', 'CNAME', '.', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'32.1.2.0.192.rpz-ip.rpz.example.net', 'CNAME', 'rpz-passthru', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'ns.example.com.rpz-nsdname.rpz.example.net', 'CNAME', '.', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'32.zz.db8.2001.rpz-nsip.rpz.example.net', 'CNAME', '.', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'A', '172.16.0.1', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'A', '172.16.0.2', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'A', '172.16.0.3', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'MX', 'mx1.example.com.rpz.example.net', 3600, 10, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'MX', 'mx2.example.com.rpz.example.net', 3600, 20, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'TXT', '"Contact Central Services"', 3600, 0, 0 from domains where name='rpz.example.net';
insert into records (domain_id, name, type,content,ttl,prio,disabled) select id ,'25.128.2.0.192.rpz-ip.rpz.example.net', 'TXT', '"Your system is infected."', 3600, 0, 0 from domains where name='rpz.example.net';
